// Code generated by "stringer -trimprefix group -type groupType"; DO NOT EDIT.

package parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[groupUnknown-0]
	_ = x[groupStruct-1]
	_ = x[groupStructKey-2]
	_ = x[groupStructValue-3]
	_ = x[groupList-4]
	_ = x[groupListValue-5]
	_ = x[groupTable-6]
	_ = x[groupTableHead-7]
	_ = x[groupTableData-8]
	_ = x[groupTableDataValue-9]
}

const _groupType_name = "UnknownStructStructKeyStructValueListListValueTableTableHeadTableDataTableDataValue"

var _groupType_index = [...]uint8{0, 7, 13, 22, 33, 37, 46, 51, 60, 69, 83}

func (i groupType) String() string {
	if i < 0 || i >= groupType(len(_groupType_index)-1) {
		return "groupType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _groupType_name[_groupType_index[i]:_groupType_index[i+1]]
}
