// Code generated by "stringer -trimprefix group -type groupType"; DO NOT EDIT.

package parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[groupUnknown-0]
	_ = x[groupStruct-1]
	_ = x[groupStructKey-2]
	_ = x[groupList-3]
	_ = x[groupValue-4]
}

const _groupType_name = "UnknownStructStructKeyListValue"

var _groupType_index = [...]uint8{0, 7, 13, 22, 26, 31}

func (i groupType) String() string {
	if i < 0 || i >= groupType(len(_groupType_index)-1) {
		return "groupType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _groupType_name[_groupType_index[i]:_groupType_index[i+1]]
}
