// Code generated by "stringer -trimprefix statement -type statementType"; DO NOT EDIT.

package parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[statementUnknown-0]
	_ = x[statementComment-1]
	_ = x[statementContext-2]
	_ = x[statementCreate-3]
	_ = x[statementSet-4]
}

const _statementType_name = "UnknownCommentContextCreateSet"

var _statementType_index = [...]uint8{0, 7, 14, 21, 27, 30}

func (i statementType) String() string {
	if i < 0 || i >= statementType(len(_statementType_index)-1) {
		return "statementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statementType_name[_statementType_index[i]:_statementType_index[i+1]]
}
