// Code generated by "stringer -trimprefix token -type tokenType"; DO NOT EDIT.

package parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenUnknown-0]
	_ = x[tokenNewline-1]
	_ = x[tokenWhitespace-2]
	_ = x[tokenIdentifier-3]
	_ = x[tokenComment-4]
	_ = x[tokenSymbol-5]
	_ = x[tokenNumber-6]
	_ = x[tokenQuote-7]
}

const _tokenType_name = "UnknownNewlineWhitespaceIdentifierCommentSymbolNumberQuote"

var _tokenType_index = [...]uint8{0, 7, 14, 24, 34, 41, 47, 53, 58}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
